[profile.default]
solc-version = '0.8.30'
src = 'src'
out = 'out'
test = 'test'
cache_path = 'cache/foundry'
optimizer = true
optimizer_runs = 200
gas_reports = ["BtcMirror", "BtcTxVerifier"]
ffi = true
ast = true
build_info = true
via_ir = true
extra_output = ["storageLayout"]

libs = [
    # Use LayerZero toolbox foundry lib which includes all necessary dependencies
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
    # Keep existing lib for OpenZeppelin
    'lib',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/',
]
